package smstwilio

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Sender implements SMS sending using Twilio's Verify API.
// Uses custom codes generated by authkit for consistency with email verification.
type Sender struct {
	AccountSID       string
	AuthToken        string
	VerifyServiceSID string
	AppName          string // App name shown in SMS messages (e.g., "MyApp Login")
	Client           *http.Client
}

// New creates a Twilio SMS sender. All parameters are required.
// appName is used in SMS messages (e.g., "MyApp Login" or "MyApp Verification")
func New(accountSID, authToken, verifyServiceSID, appName string) *Sender {
	return &Sender{
		AccountSID:       accountSID,
		AuthToken:        authToken,
		VerifyServiceSID: verifyServiceSID,
		AppName:          appName,
	}
}

func (s *Sender) httpClient() *http.Client {
	if s.Client != nil {
		return s.Client
	}
	return &http.Client{Timeout: 10 * time.Second}
}

// SendVerificationCode sends a 6-digit verification code via Twilio Verify API
// Uses custom_code to maintain consistency with authkit's code generation
func (s *Sender) SendVerificationCode(ctx context.Context, phone, code string) error {
	return s.sendVerifyCode(ctx, phone, code, "verification")
}

// SendLoginCode sends a 2FA login code via Twilio Verify API
func (s *Sender) SendLoginCode(ctx context.Context, phone, code string) error {
	return s.sendVerifyCode(ctx, phone, code, "login")
}

// sendVerifyCode sends a verification using Twilio Verify API with custom code
// See: https://www.twilio.com/docs/verify/api/verification
func (s *Sender) sendVerifyCode(ctx context.Context, to, code, purpose string) error {
	apiURL := fmt.Sprintf("https://verify.twilio.com/v2/Services/%s/Verifications", s.VerifyServiceSID)

	// Verify API requires form-encoded data
	formData := url.Values{}
	formData.Set("To", to)
	formData.Set("Channel", "sms")
	formData.Set("CustomCode", code) // Use authkit-generated code

	// Optional: Set custom friendly name for better user experience
	if s.AppName != "" {
		if purpose == "login" {
			formData.Set("CustomFriendlyName", s.AppName+" Login")
		} else {
			formData.Set("CustomFriendlyName", s.AppName+" Verification")
		}
	}

	req, err := http.NewRequestWithContext(ctx, "POST", apiURL, strings.NewReader(formData.Encode()))
	if err != nil {
		return err
	}

	req.SetBasicAuth(s.AccountSID, s.AuthToken)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := s.httpClient().Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		return nil
	}

	// Parse error response
	var errResp struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&errResp); err == nil {
		return fmt.Errorf("twilio verify error %d: %s", errResp.Code, errResp.Message)
	}

	return fmt.Errorf("twilio verify error: status %d", resp.StatusCode)
}
